name: JavaScript-release

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: (cd javascript && yarn install && yarn run build)
      - name: Publish
        run: (cd javascript && yarn publish --non-interactive --access public)
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}