name: PHP-release

on:
  push:
    tags:        
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create package
        run: (cd php && zip -r -q ../wikicodeparser-php.zip src/ composer.json composer.lock)
      - name: Upload file
        uses: softprops/action-gh-release@v1
        with:
          files: wikicodeparser-php.zip